services:
  app:
    container_name: nvim-application
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - ./dap.lua:/root/.config/nvim/lua/plugins/dap.lua
    command: ['tail', '-f', '/dev/null']
